##
## This file is part of the libopencm3 project.
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

BINARY = main
OBJS += usb-gadget0.o
OBJS += trace.o trace_stdio.o

CFLAGS += -std=gnu99
#CFLAGS += -I../shared
#VPATH += ../shared/

LDSCRIPT = ../../examples/stm32/f4/stm32f4-discovery/stm32f4-discovery.ld

LIBNAME         = opencm3_stm32f4
DEFS            = -DSTM32F4

FP_FLAGS        ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS      = -mthumb -mcpu=cortex-m4 $(FP_FLAGS)

OOCD            ?= openocd
OOCD_INTERFACE  ?= stlink-v2
OOCD_BOARD      ?= stm32f4discovery

OPENCM3_DIR=../../libopencm3
include ../../examples/Makefile.rules

